# clusterissuer-lets-encrypt-staging.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: win@kenzoo.net
    privateKeySecretRef:
      name: letsencrypt-account-private-key
    solvers:
      - http01:
          ingress:
            class: nginx
      # - dns01:
      #     route53:
      #       region: ${AWS_DEFAULT_REGION}
      #       role: arn:aws:iam::${AWS_ACCOUNT_ID}:role/cert-manager-acme-dns01-route53
      #       auth:
      #         kubernetes:
      #           serviceAccountRef:
      #             name: cert-manager-acme-dns01-route53
